services:
  - type: worker
    name: sure-x-password-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_CHAT_ID
        sync: false
